import type { Metadata } from "next";
import "./globals.css";
import { SocketProvider } from "@/components/SocketProvider";

export const metadata: Metadata = {
  title: "Dice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="flex flex-col h-full">
        <SocketProvider>
          {children}
        </SocketProvider>
      </body>
    </html>
  );
}
