import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="flex flex-col h-full">
        {children}
      </body>
    </html>
  );
}
