services:
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    volumes:
      - ./web:/usr/share/nginx/html/:ro
    restart: unless-stopped
    networks:
      - web
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    env_file:
     - .env
    depends_on:
     - nginx
    command: tunnel --no-autoupdate --url http://nginx:80
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge

    # docker run 
    # cloudflare/cloudflared:latest 
    # tunnel --no-autoupdate run --token