import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPolitics() {
	return (
		<main className="min-h-screen bg-background text-foreground py-12 px-4 sm:px-6">
			<article className="max-w-3xl mx-auto space-y-8 text-muted-foreground leading-relaxed">
				{/* Header */}
				<header className="space-y-2 border-b border-border pb-6">
					<h1 className="text-3xl font-bold tracking-tight text-foreground">
						Privacy Policy
					</h1>
					<p className="text-sm">Last updated: September 25, 2026</p>
				</header>

				{/* Content */}
				<section className="space-y-4">
					<p>
						This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
					</p>
					<p>
						We use Your Personal Data to provide and improve the Service. We collect, use, and disclose Your information as described in this Privacy Policy and, where required by applicable law, only where We have a valid legal basis to do so, including Your consent (where consent is required). This Privacy Policy has been created with the help of the{" "}
						<a
							href="https://www.termsfeed.com/privacy-policy-generator/"
							target="_blank"
							rel="noreferrer"
							className="text-foreground underline underline-offset-4 hover:text-primary"
						>
							Privacy Policy Generator
						</a>.
					</p>
				</section>

				<section className="space-y-4 pt-4">
					<h2 className="text-xl font-semibold text-foreground">Interpretation and Definitions</h2>

					<div className="space-y-2">
						<h3 className="text-lg font-medium text-foreground">Interpretation</h3>
						<p>
							The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
						</p>
					</div>

					<div className="space-y-3">
						<h3 className="text-lg font-medium text-foreground">Definitions</h3>
						<p>For the purposes of this Privacy Policy:</p>
						<ul className="list-disc pl-5 space-y-2">
							<li><strong className="text-foreground">Account</strong> means a unique account created for You to access Our Service or parts of Our Service.</li>
							<li><strong className="text-foreground">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
							<li><strong className="text-foreground">Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Dice.</li>
							<li><strong className="text-foreground">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website, among its many uses.</li>
							<li><strong className="text-foreground">Country/State</strong> refers to: Catalonia.</li>
							<li><strong className="text-foreground">Device</strong> means any device that can access the Service, such as a computer, a cell phone or a digital tablet.</li>
							<li>
								<strong className="text-foreground">Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual.
								<p className="mt-1">We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</p>
							</li>
							<li><strong className="text-foreground">Service</strong> refers to the Website.</li>
							<li><strong className="text-foreground">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
							<li><strong className="text-foreground">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
							<li><strong className="text-foreground">User</strong> means any individual who accesses or uses the Service.</li>
							<li>
								<strong className="text-foreground">Website</strong> refers to Dice, accessible from{" "}
								<a href="https://dice.eina.cc/" rel="external nofollow noopener" target="_blank" className="text-foreground underline underline-offset-4 hover:text-primary">
									https://dice.eina.cc/
								</a>.
							</li>
							<li><strong className="text-foreground">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
						</ul>
					</div>
				</section>

				<section className="space-y-4 pt-4">
					<h2 className="text-xl font-semibold text-foreground">Collecting and Using Your Personal Information</h2>

					<h3 className="text-lg font-medium text-foreground">Types of Data Collected</h3>

					<div className="space-y-2">
						<h4 className="font-medium text-foreground">Personal Data</h4>
						<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
						<ul className="list-disc pl-5">
							<li>Email address</li>
						</ul>
					</div>

					<div className="space-y-2">
						<h4 className="font-medium text-foreground">Usage Data</h4>
						<p>Usage Data is collected automatically when using the Service.</p>
						<p>Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of Our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
						<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device&apos;s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
						<p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>
					</div>

					<div className="space-y-2">
						<h4 className="font-medium text-foreground">Tracking Technologies and Cookies</h4>
						<p>We use tracking technologies (such as cookies) to track the activity and to improve Our Service. The technologies We use may include:</p>
						<ul className="list-disc pl-5 space-y-2">
							<li><strong className="text-foreground">Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of Our Service.</li>
							<li><strong className="text-foreground">Web Beacons.</strong> Certain sections of Our Service may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
						</ul>
						<p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
						<p>Where required by law, We use non-essential cookies (that is, Cookies other than the Necessary / Essential Cookies described below) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
						<p>We use both Session and Persistent Cookies for the purposes set out below:</p>

						<ul className="list-disc pl-5 space-y-3 pt-2">
							<li>
								<p><strong className="text-foreground">Necessary / Essential Cookies</strong></p>
								<p className="text-xs">Type: Session Cookies | Administered by: Us</p>
								<p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
							</li>
							<li>
								<p><strong className="text-foreground">Cookies Policy / Notice Acceptance Cookies</strong></p>
								<p className="text-xs">Type: Persistent Cookies | Administered by: Us</p>
								<p>Purpose: These Cookies identify whether users have accepted the use of cookies on the Website and record the consent choices You have made, so that We can honor those choices on future visits.</p>
							</li>
							<li>
								<p><strong className="text-foreground">Functionality Cookies</strong></p>
								<p className="text-xs">Type: Persistent Cookies | Administered by: Us</p>
								<p>Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering Your Account login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter Your preferences every time You use the Website.</p>
							</li>
						</ul>
					</div>

					<div className="space-y-3 pt-2">
						<h3 className="text-lg font-medium text-foreground">Use of Your Personal Data</h3>
						<p>The Company may use Personal Data for the following purposes:</p>
						<ul className="list-disc pl-5 space-y-2">
							<li><strong className="text-foreground">To provide and maintain Our Service</strong>, including to monitor the usage of Our Service.</li>
							<li><strong className="text-foreground">To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
							<li><strong className="text-foreground">For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
							<li><strong className="text-foreground">To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
							<li><strong className="text-foreground">To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that You have already purchased or inquired about. We send such marketing communications only where permitted by applicable law: where prior consent is required (for example, under the laws applicable in the EEA and the UK), We will send them only with Your consent; otherwise, We may send them until You opt out. You may opt out or withdraw Your consent at any time by using the unsubscribe link in any marketing email We send or by contacting Us.</li>
							<li><strong className="text-foreground">To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
							<li><strong className="text-foreground">For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about Our Service users is among the assets transferred.</li>
							<li><strong className="text-foreground">For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of Our promotional campaigns, and evaluating and improving Our Service, products, services, marketing and Your experience.</li>
						</ul>

						<p className="pt-2">We may share Your Personal Data in the following situations:</p>
						<ul className="list-disc pl-5 space-y-1">
							<li><strong className="text-foreground">With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of Our Service, and to contact You.</li>
							<li><strong className="text-foreground">For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
							<li><strong className="text-foreground">With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case We will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
							<li><strong className="text-foreground">With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside the Service.</li>
							<li><strong className="text-foreground">With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
						</ul>
					</div>

					<div className="space-y-2 pt-2">
						<h4 className="font-medium text-foreground">Text Messages Privacy Notice</h4>
						<p>You have the option to receive text (SMS) messages from Us. If You opt in to text messages, We will send You updates, notifications, and other communications as described below. When You opt in, We will collect and store the information You provide in connection with text messaging, such as Your phone number, the date and method of Your consent, and message delivery and read information.</p>
						<p>No mobile information will be shared with or sold to third parties or affiliates for marketing or promotional purposes. The phone numbers and consent records We collect for texting are never shared with anyone for any purpose, except the Service Providers that technically have to handle them to deliver the texts.</p>
						<p>Consent to receive text messages is not a condition of any purchase or use of Our Service. If You consent to receive SMS from Us, You agree to receive text messages from Us related to:</p>
						<ul className="list-disc pl-5 space-y-1">
							<li>Customer care and support</li>
							<li>Account notifications, such as activity, status, or renewal reminders</li>
							<li>Delivery notifications and updates on the status of a delivery</li>
							<li>Authentication messages, such as one-time passwords (OTP) and passcodes</li>
							<li>Security alerts, such as suspicious login attempts or unusual account activity</li>
							<li>Marketing and promotional offers, discounts, and other promotional content</li>
						</ul>
						<p className="text-xs italic pt-1">Reply STOP to opt-out. Reply HELP for support. Message &amp; data rates may apply. Messaging frequency may vary. Carriers are not liable for delayed or undelivered messages.</p>
					</div>

					<div className="space-y-3 pt-2">
						<h3 className="text-lg font-medium text-foreground">Retention of Your Personal Data</h3>
						<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with Our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce Our legal agreements and policies.</p>
						<p>Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods (&quot;up to&quot;) and We may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>

						<ul className="list-disc pl-5 space-y-2">
							<li>
								<strong className="text-foreground">Account Information:</strong> User Accounts are retained for the duration of Your Account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes.
							</li>
							<li>
								<strong className="text-foreground">Customer Support Data:</strong> Support tickets and correspondence up to 24 months from closure. Chat transcripts up to 24 months for quality assurance.
							</li>
							<li>
								<strong className="text-foreground">Usage Data:</strong> Website analytics data and server logs up to 24 months from collection for security and analytics.
							</li>
						</ul>

						<p>Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance.</p>
						<p>We may retain Personal Data beyond the periods stated above for legal obligations, legal claims, explicit requests, or technical limitations in backups.</p>
						<p>When retention periods expire, We securely delete, anonymize, or isolate Personal Data in encrypted backups until routine deletion.</p>
					</div>

					<div className="space-y-2 pt-2">
						<h3 className="text-lg font-medium text-foreground">Transfer of Your Personal Data</h3>
						<p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It may be transferred to — and maintained on — computers located outside of Your jurisdiction.</p>
						<p>Where required by law, We ensure international transfers are subject to appropriate safeguards and adequate controls.</p>
					</div>

					<div className="space-y-2 pt-2">
						<h3 className="text-lg font-medium text-foreground">Delete Your Personal Data</h3>
						<p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
						<p>You may update, amend, or delete Your information at any time by signing in to Your Account or contacting Us directly.</p>
					</div>

					<div className="space-y-2 pt-2">
						<h3 className="text-lg font-medium text-foreground">Disclosure of Your Personal Data</h3>
						<p><strong className="text-foreground">Business Transactions:</strong> Your data may be transferred during a merger, acquisition, or asset sale with prior notice.</p>
						<p><strong className="text-foreground">Law Enforcement:</strong> We may disclose data if required by law or valid requests by public authorities.</p>
						<p><strong className="text-foreground">Other Legal Requirements:</strong> Data may be disclosed to comply with legal obligations, protect rights/property, prevent wrongdoing, or defend liability.</p>
					</div>

					<div className="space-y-2 pt-2">
						<h3 className="text-lg font-medium text-foreground">Security of Your Personal Data</h3>
						<p>While We strive to use commercially reasonable means to protect Your Personal Data, no method of transmission over the Internet is 100% secure.</p>
					</div>
				</section>

				<section className="space-y-2 pt-4">
					<h2 className="text-xl font-semibold text-foreground">Children&apos;s and Minors&apos; Privacy</h2>
					<p>The Service is not directed to anyone under the age of 16. If We become aware that We have collected Personal Information from anyone under 16 without parental consent, We take steps to remove that information.</p>
				</section>

				<section className="space-y-2 pt-4">
					<h2 className="text-xl font-semibold text-foreground">Links to Other Websites</h2>
					<p>Our Service may contain links to third-party sites. We have no control over and assume no responsibility for the content or practices of any third-party sites.</p>
				</section>

				<section className="space-y-2 pt-4">
					<h2 className="text-xl font-semibold text-foreground">Changes to this Privacy Policy</h2>
					<p>We may update Our Privacy Policy from time to time and will notify You by posting the new policy on this page with an updated date.</p>
				</section>

				<footer className="pt-6 border-t border-border space-y-2">
					<h2 className="text-xl font-semibold text-foreground">Contact Us</h2>
					<p>If You have any questions about this Privacy Policy, You can contact Us:</p>
					<ul className="list-disc pl-5">
						<li>
							By email:{" "}
							<a href="mailto:pamanzan@student.42barcelona.com" className="text-foreground underline hover:text-primary">
								pamanzan@student.42barcelona.com
							</a>
						</li>
					</ul>
				</footer>

			</article>
		</main>
	);
}