services:
  db:
    image: postgres:17-alpine
    container_name: transcendence-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - transcendence-net

  next-app:
    build:
      context: .
      dockerfile: next/Dockerfile
      target: dev # canviar a prod per entregar
    container_name: transcendence-app
    restart: no
    stop_grace_period: 5s
    volumes:
      # surgical bind mounts for hot-reload
      - ./next/app:/app/app
      - ./next/components:/app/components
      - ./next/lib:/app/lib
      - ./next/hooks:/app/hooks
      - ./next/public:/app/public
      - ./next/next.config.ts:/app/next.config.ts
      # prisma schema + migrations for migrate deploy at runtime
      - ./prisma:/app/prisma:ro
      # named volumes for generated/build content (fast + persistent)
      - next-modules:/app/node_modules
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    env_file: ".env.local"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence-net

  socket:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server-backend
    restart: no
    volumes:
      - server-modules:/server/node_modules
      - ./server/sockets:/server/sockets
      - ./server/game:/server/game
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      AUTH_INTERNAL_URL: http://next-app:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence-net

  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: no
    security_opt:
      - no-new-privileges:true

    networks:
      - transcendence-net

    ports:
      - "8000:8000"
      - "8443:8443"

    volumes:
      - ./certs:/certs:ro
      - ./traefik:/dynamic:ro

    command:
      # EntryPoints
      - "--entrypoints.web.address=:8000"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.websecure.http.tls=true"

      - "--providers.file.filename=/dynamic/config.yaml"

      # API & Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"

  newt:
    image: fosrl/newt
    container_name: newt
    restart: no
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
    depends_on:
      next-app:
        condition: service_started
      socket:
        condition: service_started
    networks:
      - transcendence-net



volumes:
  db-data:
  next-modules:
  server-modules:
  prisma-client-app:
  prisma-client-server:

networks:
  transcendence-net:
