services:
  next-app:
    container_name: transcendence-app
    build:
      context: ./srcs
      dockerfile: Dockerfile

    env_file:
      - ./srcs/.env.local

    environment:
      WATCHPACK_POLLING: "true"

    volumes:
      - ./srcs:/app
      - /app/node_modules

    ports:
      - "3000:3000"