services:
  next-app:
    container_name: transcendence-app
    build:
      context: ./srcs
      dockerfile: Dockerfile
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - ./srcs:/app
      - /app/node_modules

    restart: no
    ports:
      - 3000:3000