import type { Metadata } from "next";
import "./globals.css";
// import AuthProvider from "@/components/AuthProvider";

export const metadata: Metadata = {
  title: "Dice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col scroll-none">
          {children}
        </body>
    </html>
  );
}

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   return (
//     <html
//       lang="en"
//       className={`h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col scroll-none">
//         <AuthProvider>
//           {children}
//         </AuthProvider>
//         </body>
//     </html>
//   );
// }
